// Code generated by mockery v1.1.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Family is an autogenerated mock type for the Family type
type Family struct {
	mock.Mock
}

// SimpleFunctionWithAnUnusuallyLongName1 provides a mock function with given fields:
func (_m *Family) SimpleFunctionWithAnUnusuallyLongName1() (map[string]string, error) {
	ret := _m.Called()

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SimpleFunctionWithAnUnusuallyLongName2 provides a mock function with given fields:
func (_m *Family) SimpleFunctionWithAnUnusuallyLongName2() (map[string]string, error) {
	ret := _m.Called()

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
